export default {
  login: 'oguzhanorh',
  id: 64217280,
  node_id: 'MDQ6VXNlcjY0MjE3Mjgw',
  avatar_url: 'https://avatars.githubusercontent.com/u/64217280?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/oguzhanorh',
  html_url: 'https://github.com/oguzhanorh',
  followers_url: 'https://api.github.com/users/oguzhanorh/followers',
  following_url:
    'https://api.github.com/users/oguzhanorh/following{/other_user}',
  gists_url: 'https://api.github.com/users/oguzhanorh/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/oguzhanorh/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/oguzhanorh/subscriptions',
  organizations_url: 'https://api.github.com/users/oguzhanorh/orgs',
  repos_url: 'https://api.github.com/users/oguzhanorh/repos',
  events_url: 'https://api.github.com/users/oguzhanorh/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/oguzhanorh/received_events',
  type: 'User',
  site_admin: false,
  name: 'Oğuzhan ORHAN',
  company: 'LST YAZILIM',
  blog: '',
  location: 'Turkey',
  email: null,
  hireable: null,
  bio: 'Full Stack Software Developer',
  twitter_username: null,
  public_repos: 15,
  public_gists: 0,
  followers: 5,
  following: 4,
  created_at: '2020-04-23T16:23:46Z',
  updated_at: '2022-06-18T13:00:49Z',
};
